#!/usr/bin/env bash
# Upload location photos lên S3
# Chạy từ thư mục gốc project: bash scripts/upload-photos-s3.sh

AWS="C:/Program Files/Amazon/AWSCLIV2/aws.exe"
BUCKET="viloca-media"
SG_DIR="assets/Sài Gòn"
DN_DIR="assets/Đà Nẵng"

upload() {
  local src="$1"
  local dest="$2"
  echo "Uploading: $dest"
  "$AWS" s3 cp "$src" "s3://$BUCKET/$dest" --quiet && echo "  ✓ OK" || echo "  ✗ FAIL"
}

echo "=== SG ==="
upload "$SG_DIR/Dinh_doc_lap.jpg"                     "locations/SG/dinh-doc-lap/1.jpg"
upload "$SG_DIR/Buu_dien_thanh_pho.jpg"               "locations/SG/buu-dien-trung-tam/1.jpg"
upload "$SG_DIR/Nha_hat_thanh_pho.jpg"                "locations/SG/nha-hat-thanh-pho/1.jpg"
upload "$SG_DIR/Bao_tang_lich_su.jpg"                 "locations/SG/bao-tang-lich-su/1.jpg"
upload "$SG_DIR/Cho_ben_thanh.jpg"                    "locations/SG/cho-ben-thanh/1.jpg"
upload "$SG_DIR/Bao_tang_chung_tich_chien_tranh.jpg"  "locations/SG/bao-tang-chung-tich/1.jpg"

echo ""
echo "=== DN ==="
upload "$DN_DIR/Dinh_doc_lap.jpg"                                          "locations/DN/dinh-doc-lap/1.jpg" 2>/dev/null
upload "$DN_DIR/trung tam van hoa du lich Ta Lang_Gian Bi.jpg"             "locations/DN/ta-lang-gian-bi/1.jpg"
upload "$DN_DIR/the_Hang_art.jpeg"                                         "locations/DN/the-hang-art/1.jpg"
upload "$DN_DIR/Lang_Loom.jpeg"                                            "locations/DN/lang-toom-sara/1.jpg"
upload "$DN_DIR/Giong_cafe.jpeg"                                           "locations/DN/giong-cafe/1.jpg"
upload "$DN_DIR/bao_tang_dieu_khac_Cham.png"                              "locations/DN/bao-tang-dieu-khac-cham/1.jpg"
upload "$DN_DIR/Lang_Cui_Lu.jpg"                                           "locations/DN/lang-cui-lu-hoi-an/1.jpg"
upload "$DN_DIR/Homestay_Alang_Nhu.jpg"                                    "locations/DN/homestay-alang-nhu/1.jpg"
upload "$DN_DIR/The_Heritage_Show.jpg"                                     "locations/DN/the-heritage-show/1.jpg"
upload "$DN_DIR/cong-vien-dat-nung-thanh-ha-0_optimized.jpg"              "locations/DN/cong-vien-dat-nung/1.jpg"
upload "$DN_DIR/Lang_moc_Kim_Bong.jpeg"                                    "locations/DN/lang-moc-kim-bong/1.jpg"
upload "$DN_DIR/ngon-pho-da-2-300-4241793773337.webp"                     "locations/DN/ngon-pho-da/1.jpg"
upload "$DN_DIR/Ky_uc_hoi_an.jpg"                                          "locations/DN/ky-uc-hoi-an/1.jpg"
upload "$DN_DIR/Hang_ganh.jpg"                                             "locations/DN/hang-ganh/1.jpg"
upload "$DN_DIR/108_nha-hang-truc-lam-vien-dn-a1.jpg"                    "locations/DN/truc-lam-vien/1.jpg"
upload "$DN_DIR/cong-troi-dong-giang-ivivu-1.jpg"                         "locations/DN/cong-troi-dong-giang/1.jpg"
upload "$DN_DIR/Ngon_thi_hoa.jpg"                                          "locations/DN/ngon-thi-hoa/1.jpg"
upload "$DN_DIR/bep_cuon.jpg"                                              "locations/DN/bep-cuon/1.jpg"
upload "$DN_DIR/bao_tang_van_hoa_Sa_Huynh.jpg"                           "locations/DN/bao-tang-sa-huynh/1.jpg"
upload "$DN_DIR/lang_rau_tra_que.jpg"                                      "locations/DN/lang-rau-tra-que/1.jpg"
upload "$DN_DIR/nha_co_tan_ky.jpeg"                                        "locations/DN/nha-co-tan-ky/1.jpg"
upload "$DN_DIR/Leaf-Village-Farm-Da-Nang-ivivu.jpg"                      "locations/DN/leaf-village-farm/1.jpg"
upload "$DN_DIR/The_farmers.jpeg"                                          "locations/DN/the-farmers/1.jpg"
upload "$DN_DIR/hoi-quan-phuc-kien-2.jpg"                                  "locations/DN/hoi-quan-phuoc-kien/1.jpg"
upload "$DN_DIR/bao-tang-dong-dinh-bia.jpg"                               "locations/DN/bao-tang-dong-dinh/1.jpg"
upload "$DN_DIR/nha_go_villa.jpg"                                          "locations/DN/nha-go-villa/1.jpg"
upload "$DN_DIR/tour-rung-dua-bay-mau-1.jpg"                              "locations/DN/rung-dua-bay-mau/1.jpg"

echo ""
echo "=== HN ==="
HN_DIR="assets/Hà Nội"
upload "$HN_DIR/bao_tang_dan_toc.jpg"                        "locations/HN/bao-tang-dan-toc/1.jpg"
upload "$HN_DIR/bao_tang_gom_bat_trang.jpg"                  "locations/HN/bao-tang-gom-bat-trang/1.jpg"
upload "$HN_DIR/canh_dong_huong_lang_quang_phu_cau.PNG"      "locations/HN/lang-nghe-quang-phu-cau/1.jpg"
upload "$HN_DIR/cau_long_bien_1.PNG"                         "locations/HN/cau-long-bien/1.jpg"
upload "$HN_DIR/cau_long_bien_2.PNG"                         "locations/HN/cau-long-bien/2.jpg"
upload "$HN_DIR/cho_dong_xuan.PNG"                           "locations/HN/cho-dong-xuan/1.jpg"
upload "$HN_DIR/cot_co_ha_noi.PNG"                           "locations/HN/cot-co-ha-noi/1.jpg"
upload "$HN_DIR/di_tich_hoa_lo.PNG"                          "locations/HN/nha-tu-hoa-lo/1.jpg"
upload "$HN_DIR/ho_hoan_kiem.jpg"                            "locations/HN/ho-hoan-kiem/1.jpg"
upload "$HN_DIR/hoanh_thanh_thang_long.PNG"                  "locations/HN/hoang-thanh-thang-long/1.jpg"
upload "$HN_DIR/lang_chu_tich_hcm.PNG"                       "locations/HN/lang-chu-tich-hcm/1.jpg"
upload "$HN_DIR/lang_chu_tich_hcm_2.PNG"                     "locations/HN/lang-chu-tich-hcm/2.jpg"
upload "$HN_DIR/lang_chu_tich_hcm_3.PNG"                     "locations/HN/lang-chu-tich-hcm/3.jpg"
upload "$HN_DIR/nha_hat_lon_ha_noi.PNG"                      "locations/HN/nha-hat-lon-ha-noi/1.jpg"
upload "$HN_DIR/nha_hat_mua_roi_nuoc_1.jpg"                  "locations/HN/nha-hat-mua-roi/1.jpg"
upload "$HN_DIR/nha_san_bac_ho.jpg"                          "locations/HN/khu-phu-chu-tich/1.jpg"
upload "$HN_DIR/o_quan_chuong.PNG"                           "locations/HN/o-quan-chuong/1.jpg"
upload "$HN_DIR/van_mieu_quoc_tu_giam.jpg"                   "locations/HN/van-mieu-quoc-tu-giam/1.jpg"

echo ""
echo "=== Festival ==="
FT_DIR="assets/Festival"
upload "$FT_DIR/tet_nguyen_dan.jpg"                   "festivals/tet-nguyen-dan.jpg"
upload "$FT_DIR/le_hoi_chua_huong.PNG"                "festivals/le-hoi-chua-huong.jpg"
upload "$FT_DIR/le_hoi_banh_mi.PNG"                   "festivals/le-hoi-banh-mi.jpg"
upload "$FT_DIR/le-hoi-cau-ngu.jpg"                   "festivals/le-hoi-cau-ngu.jpg"
upload "$FT_DIR/gio_to_hung_vuong.PNG"                "festivals/gio-to-hung-vuong.jpg"
upload "$FT_DIR/dai_le_phat_dan.PNG"                  "festivals/dai-le-phat-dan.jpg"
upload "$FT_DIR/tet-doan-ngo.jpg"                     "festivals/tet-doan-ngo.jpg"
upload "$FT_DIR/Le-hoi-den-long-hoi-an.jpg"           "festivals/festival-den-long-hoi-an.jpg"
upload "$FT_DIR/vu-lan-bao-hieu.jpg"                  "festivals/vu-lan-bao-hieu.jpg"
upload "$FT_DIR/tet_trung_thu_pho_co_hoi_an.jpg"      "festivals/trung-thu-hoi-an.jpg"
upload "$FT_DIR/tet_trung_thu_pho_co_ha_noi.PNG"      "festivals/trung-thu-ha-noi.jpg"
upload "$FT_DIR/le-hoi-ao-dai-tphcm.jpg"              "festivals/le-hoi-ao-dai-tphcm.jpg"
upload "$FT_DIR/dem_rang_pho_co_hoi_an.jpg"           "festivals/dem-ram-pho-co-hoi-an.jpg"
upload "$FT_DIR/Cho_hoa_tet_hang_luoc.jpg"            "festivals/cho-hoa-tet-hang-luoc.jpg"
upload "$FT_DIR/duong_hoa_nguyen_hue.PNG"             "festivals/duong-hoa-nguyen-hue.jpg"

echo ""
echo "=== Xong ==="
