-- Seed: Hanoi (HN) locations
INSERT INTO locations (city, name, district, address, google_maps_url, category, style_tag, price_level, opening_hours, closing_hours, off_days, phone, short_description, long_description, photos, verified, is_active)
VALUES
  (
    'HN', 'Nhà Hát Múa Rối Thăng Long', 'Hoàn Kiếm',
    '57B Đinh Tiên Hoàng, Hoàn Kiếm, Hà Nội',
    'https://maps.app.goo.gl/K1RpyoomZb4bdzVG7',
    'Trải nghiệm, Nghệ thuật',
    'Biểu diễn, Múa rối nước, Truyền thống, Dân gian',
    2, 'T2-T7 15:00 / CN 09:30', 'T2-T7 20:50 / CN 22:05', 'Không rõ', '+84 86 686 4867',
    'Nhà hát múa rối nằm bên hồ Hoàn Kiếm — nơi thưởng thức nghệ thuật dân gian đặc sắc qua những con rối gỗ và âm nhạc truyền thống.',
    'Nhà hát múa rối Thăng Long là một trong những không gian nghệ thuật truyền thống tiêu biểu của Hà Nội. Với nhiều chương trình biểu diễn đa dạng, từ múa rối nước đến múa rối cạn, nhà hát tái hiện sinh động những câu chuyện dân gian, phong tục và đời sống văn hóa Việt Nam. Đồng hành cùng mỗi tiết mục là âm nhạc truyền thống với tiếng trống, đàn nhị, sáo và những làn điệu dân gian đặc trưng.',
    NULL, true, true
  ),
  (
    'HN', 'Trung Tâm Văn Hóa Nghệ Thuật 22 Hàng Buồm', 'Hoàn Kiếm',
    '22 P. Hàng Buồm, Phố cổ Hà Nội, Hoàn Kiếm, Hà Nội',
    'https://maps.app.goo.gl/qYSmhkeRJu7hDF2Y9',
    'Tham quan, Nghệ thuật',
    'Triển lãm, Kiến trúc, Nghệ thuật, Truyền thống, Chụp ảnh',
    1, '08:00', 'T2-T5 17:30 / T6-CN 21:00', 'Không rõ', NULL,
    'Không gian văn hóa và nghệ thuật nằm giữa Phố cổ Hà Nội — nơi thường xuyên diễn ra các triển lãm và sự kiện văn hóa đa dạng.',
    'Trung tâm Văn hóa Nghệ thuật 22 Hàng Buồm được cải tạo từ Hội quán Quảng Đông cổ có lịch sử hàng trăm năm. Với sự giao thoa hài hoà giữa kiến trúc cổ kính và hơi thở nghệ thuật đương đại, nơi đây thường xuyên tổ chức các triển lãm, chương trình nghệ thuật, hoạt động sáng tạo và sự kiện văn hóa dành cho cộng đồng.',
    NULL, true, true
  ),
  (
    'HN', 'Bảo Tàng Dân Tộc Học Việt Nam', 'Nghĩa Đô',
    'Đ. Nguyễn Văn Huyên, Nghĩa Đô, Hà Nội',
    'https://maps.app.goo.gl/xeYVWJQmPAMMKjsU7',
    'Tham quan, Lịch sử',
    'Triển lãm, Bảo tàng, Dân tộc, Giáo dục, Chụp ảnh',
    1, '08:30', '17:30', 'Thứ 2, Tết Nguyên Đán', '+84 24 3756 2193',
    'Bảo tàng hàng đầu về văn hóa 54 dân tộc Việt Nam — khám phá đời sống và kiến trúc truyền thống qua những không gian trưng bày sống động.',
    'Bảo tàng Dân tộc học Việt Nam là một trong những điểm đến văn hóa tiêu biểu của Hà Nội, lưu giữ và giới thiệu những giá trị đặc sắc của 54 dân tộc trên khắp Việt Nam. Bên cạnh hệ thống trưng bày hiện vật phong phú, bảo tàng còn tái hiện nhiều loại hình nhà ở truyền thống ngoài trời. Các hoạt động trình diễn, workshop thủ công và chương trình văn hóa theo mùa giúp du khách tương tác sâu hơn về sự đa dạng văn hóa Việt Nam.',
    NULL, true, true
  ),
  (
    'HN', 'Làng Nghề Tăm Hương Quảng Phú Cầu', 'Ứng Hòa',
    'Đ. 429, Cầu Bầu, Ứng Hòa, Hà Nội',
    'https://maps.app.goo.gl/8AFFwcXqnr4G7mP69',
    'Tham quan, Trải nghiệm',
    'Làng nghề truyền thống, Làm hương, Chụp ảnh, Check-in',
    1, '06:00', '18:00', 'Không nghỉ', '+84 98 538 4098',
    'Làng nghề hơn 100 năm tuổi ở ngoại thành Hà Nội — khám phá quy trình làm hương và chiêm ngưỡng sân phơi hương rực rỡ sắc màu.',
    'Làng hương Quảng Phú Cầu là một trong những làng nghề làm hương truyền thống lâu đời của miền Bắc với lịch sử hơn một thế kỷ. Du khách có thể quan sát từng công đoạn thủ công, từ chẻ tăm, nhuộm màu, se hương đến phơi khô dưới nắng — tạo nên những khung cảnh rực rỡ đặc trưng đã trở thành dấu ấn của Quảng Phú Cầu.',
    NULL, true, true
  ),
  (
    'HN', 'Cột Cờ Hà Nội (Kỳ Đài)', 'Ba Đình',
    '28A Điện Biên Phủ, Điện Biên, Ba Đình, Hà Nội',
    NULL,
    'Di tích lịch sử, Kiến trúc',
    'Hoài cổ, Kiến trúc, Lịch sử',
    1, '08:00', '17:00', 'Không nghỉ', NULL,
    'Tháp cờ cổ hơn 200 năm tuổi — một trong những công trình còn nguyên vẹn nhất của thành Hà Nội cổ.',
    'Một trong những công trình còn nguyên vẹn nhất của thành Hà Nội cổ — có thể leo lên đỉnh tháp ngắm toàn cảnh khu Ba Đình. Nằm ngay gần khuôn viên Hoàng thành nên thường được kết hợp tham quan cùng nhau.',
    NULL, true, true
  ),
  (
    'HN', 'Bảo Tàng Gốm Bát Tràng', 'Gia Lâm',
    'Số 28, thôn 5, đường Bát Tràng, xã Bát Tràng, Gia Lâm, Hà Nội',
    'https://www.google.com/maps/search/?api=1&query=B%E1%BA%A3o+t%C3%A0ng+g%E1%BB%91m+B%C3%A1t+Tr%C3%A0ng',
    'Tham quan, Trải nghiệm',
    'Làng nghề, Gốm sứ, Bảo tàng, Sáng tạo, Check-in',
    1, '08:00', '17:30', 'Không nghỉ', NULL,
    'Bảo tàng gốm 6 tầng hình bàn xoay — có khu tự nặn gốm và café tầng 4 nhìn xuống làng Bát Tràng.',
    'Công trình hoạt động từ tháng 4/2022, lấy cảm hứng từ bàn xoay gốm. Có khu trải nghiệm tự tay nặn gốm và mang sản phẩm về. Kết hợp tham quan làng gốm Bát Tràng lâu đời xung quanh.',
    NULL, true, true
  ),
  (
    'HN', 'Đình Vạn Phúc & Con Đường Ô', 'Hà Đông',
    'Phường Vạn Phúc, Hà Đông, Hà Nội',
    'https://www.google.com/maps/search/?api=1&query=%C4%90%C3%ACnh+V%E1%BA%A1n+Ph%C3%BAc',
    'Làng nghề, Di tích',
    'Làng nghề, Lụa, Check-in, Hoài cổ',
    1, '07:00', '18:00', 'Không nghỉ', NULL,
    'Đình cổ thế kỷ 16 và con đường treo ô màu sắc — điểm check-in nổi tiếng nhất của làng lụa lâu đời nhất Việt Nam.',
    'Đình Vạn Phúc thờ Thành hoàng làng, nằm giữa làng lụa Vạn Phúc — làng nghề dệt lụa có từ hơn 1.200 năm trước. Ngay gần đó là con đường ô nhiều màu trở thành điểm chụp ảnh biểu tượng. Khu chợ lụa quanh đình là nơi mua lụa tơ tằm chính gốc.',
    NULL, true, true
  ),
  (
    'HN', 'Làng Cổ Đường Lâm (Đình Mông Phụ & Nhà Cổ)', 'Sơn Tây',
    'Thôn Mông Phụ, làng cổ Đường Lâm, Sơn Tây, Hà Nội',
    'https://www.google.com/maps/search/?api=1&query=%C4%90%C3%ACnh+M%C3%B4ng+Ph%E1%BB%A5',
    'Di tích, Kiến trúc cổ',
    'Hoài cổ, Di sản, Kiến trúc đá ong, Làng cổ',
    1, '07:30', '17:30', 'Không nghỉ', NULL,
    'Làng cổ đá ong duy nhất còn giữ nguyên vẹn ở Việt Nam — đình làng 380 năm tuổi và những ngôi nhà cổ từ thế kỷ 17 vẫn có người ở.',
    'Đường Lâm là làng cổ đặc biệt với kiến trúc nhà đá ong đặc trưng của vùng Sơn Tây. Đình Mông Phụ (380 năm tuổi) nằm ở trung tâm làng còn lưu giữ nhiều hoành phi câu đối cổ. Nhà cổ ông Hùng xây năm 1649 — gần 400 năm tuổi vẫn được gia đình gìn giữ và thường kể lịch sử cho khách tham quan.',
    NULL, true, true
  ),
  (
    'HN', 'Cầu Long Biên', 'Hoàn Kiếm / Long Biên',
    'Cầu Long Biên, nối phố cổ với quận Long Biên, Hà Nội',
    'https://www.google.com/maps/search/?api=1&query=C%E1%BA%A7u+Long+Bi%C3%AAn',
    'Di tích lịch sử, Kiến trúc',
    'Hoài cổ, Kiến trúc Pháp, Đi bộ, Hoàng hôn',
    1, '00:00', '24:00', 'Không nghỉ', NULL,
    'Cầu sắt do Gustave Eiffel thiết kế — vẫn còn được sử dụng cho tàu hỏa và xe máy với tầm nhìn hùng vĩ ra sông Hồng.',
    'Một trong những công trình biểu tượng của Hà Nội, hoàn thành năm 1902. Có thể đi bộ ra giữa cầu để ngắm hoàng hôn trên sông Hồng và quan sát đời sống ven sông đặc trưng của Hà Nội. Kết hợp khám phá bãi giữa sông Hồng phía dưới.',
    NULL, true, true
  ),
  (
    'HN', 'Dự Án Nghệ Thuật Công Cộng Phúc Tân', 'Hoàn Kiếm',
    'Phường Phúc Tân, ven sông Hồng, Hoàn Kiếm, Hà Nội',
    'https://www.google.com/maps/search/?api=1&query=ngh%E1%BB%87+thu%E1%BA%ADt+Ph%C3%BAc+T%C3%A2n',
    'Nghệ thuật đương đại, Trải nghiệm',
    'Hidden, Nghệ thuật, Tái chế, Ngoài trời',
    1, '00:00', '24:00', 'Không nghỉ', NULL,
    '16 tác phẩm nghệ thuật công cộng dọc bờ sông — làm từ vật liệu tái chế bởi 16 nghệ sĩ Việt Nam năm 2020.',
    'Dự án biến một bức tường lấn chiếm ven sông Hồng thành không gian nghệ thuật mở, kết hợp khéo léo giữa thông điệp môi trường và nghệ thuật đương đại. Một số tác phẩm đã xuống cấp theo thời gian — nên kết hợp tham quan vào ban ngày.',
    NULL, false, true
  ),
  (
    'HN', 'Chợ Đồng Xuân', 'Hoàn Kiếm',
    'Phố Đồng Xuân, Hoàn Kiếm, Hà Nội',
    'https://www.google.com/maps/search/?api=1&query=Ch%E1%BB%A3+%C4%90%E1%BB%93ng+Xu%C3%A2n',
    'Chợ truyền thống, Văn hóa',
    'Local market, Lịch sử, Nhộn nhịp, Đa dạng',
    1, '06:00', '22:00', 'Không nghỉ', NULL,
    'Chợ bán buôn lớn và biểu tượng nhất Hà Nội xây từ năm 1889 — chứng tích lịch sử với trận đánh nổi tiếng năm 1947.',
    'Một trong những khu chợ cổ và nổi tiếng nhất Hà Nội. Khu ẩm thực trong ngõ chợ mở tới rạng sáng với đủ loại món ăn đường phố địa phương. Chợ là chứng tích lịch sử gắn với cuộc kháng chiến năm 1947, nay là trung tâm buôn bán sôi động của phố cổ.',
    NULL, true, true
  ),
  (
    'HN', 'Chợ Đêm Phố Cổ (Hàng Đào - Đồng Xuân)', 'Hoàn Kiếm',
    'Phố Hàng Đào kéo dài tới chợ Đồng Xuân, qua Hàng Ngang, Hà Nội',
    'https://www.google.com/maps/search/?api=1&query=ch%E1%BB%A3+%C4%91%C3%AAm+ph%E1%BB%91+c%E1%BB%95+H%C3%A0+N%E1%BB%99i',
    'Chợ truyền thống, Về đêm',
    'Local market, Về đêm, Nhộn nhịp, Đi bộ',
    1, '19:00', '23:00', 'Chỉ mở T6, T7, CN', NULL,
    'Chợ đêm cuối tuần dọc tuyến phố cổ — bán quà lưu niệm, quần áo và đồ ăn vặt khi phố quanh Hồ Gươm cấm xe.',
    'Tuyến chợ đêm chính thức chỉ mở 3 ngày cuối tuần — trùng với khung giờ phố đi bộ Hồ Hoàn Kiếm. Không khí lễ hội với người dân địa phương và du khách cùng nhau dạo chợ, ăn vặt và ngắm phố cổ về đêm.',
    NULL, true, true
  ),
  (
    'HN', 'Đền Quán Thánh', 'Ba Đình',
    'Đường Thanh Niên, Quán Thánh, Ba Đình, Hà Nội',
    'https://www.google.com/maps/search/?api=1&query=%C4%90%E1%BB%81n+Qu%C3%A1n+Th%C3%A1nh',
    'Di tích tín ngưỡng, Kiến trúc',
    'Hoài cổ, Tâm linh, Tứ trấn Thăng Long, Yên tĩnh',
    1, '08:00', '17:00', 'Không nghỉ', NULL,
    'Một trong Tứ trấn Thăng Long — ngôi đền cổ thờ Huyền Thiên Trấn Vũ đẹp đặc biệt vào buổi chiều tà ven Hồ Tây.',
    'Đền cổ thờ Huyền Thiên Trấn Vũ, trấn giữ phía Bắc kinh thành Thăng Long. Nằm ngay trên đường Thanh Niên giữa Hồ Tây và Hồ Trúc Bạch — nên ghé vào lúc chiều tà để cảm nhận không khí tĩnh lặng và ánh nắng chiều phản chiếu trên mặt hồ.',
    NULL, true, true
  ),
  (
    'HN', 'Hanoi Ca Trù Club (Đền Kim Ngân)', 'Hoàn Kiếm',
    '42 Hàng Bạc, Hoàn Kiếm, Hà Nội',
    'https://www.google.com/maps/search/?api=1&query=Hanoi+Ca+Tru+Club',
    'Nghệ thuật dân gian, Biểu diễn',
    'Biểu diễn, Di sản, Cổ kính, Âm nhạc truyền thống',
    2, '20:00', '21:30', 'Không cố định (3 buổi/tuần)', NULL,
    'Biểu diễn ca trù trong ngôi đền 500 năm tuổi — loại hình nghệ thuật UNESCO được trình diễn ngay giữa lòng phố cổ.',
    'Ca trù là loại hình nghệ thuật truyền thống độc đáo của Việt Nam được UNESCO công nhận là Di sản văn hóa phi vật thể. Được trình diễn ngay trong không gian cổ kính của đền Kim Ngân giữa phố Hàng Bạc — kết hợp tiếng phách, đàn đáy và giọng hát điêu luyện.',
    NULL, true, true
  ),
  (
    'HN', 'Ô Quan Chưởng', 'Hoàn Kiếm',
    'Phố Hàng Chiếu (góc Đào Duy Từ), Hoàn Kiếm, Hà Nội',
    'https://www.google.com/maps/search/?api=1&query=%C3%94+Quan+Ch%C6%B0%E1%BB%9Fng',
    'Di tích lịch sử, Kiến trúc',
    'Hoài cổ, Kiến trúc, Lịch sử',
    1, '00:00', '24:00', 'Không nghỉ', NULL,
    'Cổng thành cổ duy nhất còn lại của kinh thành Thăng Long xưa — di tích nhỏ nhưng có giá trị lịch sử lớn.',
    'Ô Quan Chưởng là cổng ô duy nhất còn tồn tại trong hệ thống thành lũy của kinh thành Thăng Long cũ. Nằm ngay đầu phố Hàng Chiếu dẫn vào khu phố cổ — là điểm chụp ảnh đẹp và gợi nhớ lịch sử Hà Nội nghìn năm tuổi.',
    NULL, true, true
  ),
  (
    'HN', 'Văn Miếu - Quốc Tử Giám', 'Đống Đa',
    '58 Quốc Tử Giám, Đống Đa, Hà Nội',
    'https://www.google.com/maps/search/?api=1&query=V%C4%83n+Mi%E1%BA%BFu+Qu%E1%BB%91c+T%E1%BB%AD+Gi%C3%A1m',
    'Di tích, Trải nghiệm',
    'Văn hóa truyền thống, Lịch sử, Kiến trúc, Thư pháp',
    1, '08:00', '17:00', 'Không nghỉ', NULL,
    'Trường đại học đầu tiên của Việt Nam — khu hồ Văn thường tổ chức lớp thư pháp chữ Nôm và Hán cho du khách trải nghiệm.',
    'Văn Miếu - Quốc Tử Giám xây dựng từ năm 1070, là trung tâm giáo dục đầu tiên và quan trọng nhất của Việt Nam phong kiến. Ngoài tham quan kiến trúc cổ 5 sân vườn, khu vực hồ Văn quanh đó thường tổ chức các lớp và gian viết thư pháp Việt và chữ Nho. Bia tiến sĩ ghi tên các trạng nguyên qua các triều đại là di sản UNESCO.',
    NULL, true, true
  ),
  (
    'HN', 'Phố Đi Bộ Hồ Hoàn Kiếm', 'Hoàn Kiếm',
    'Các phố quanh Hồ Hoàn Kiếm, Đinh Tiên Hoàng, Hà Nội',
    'https://www.google.com/maps/search/?api=1&query=ph%E1%BB%91+%C4%91i+b%E1%BB%99+H%E1%BB%93+Ho%C3%A0n+Ki%E1%BA%BFm',
    'Trải nghiệm địa phương, Về đêm',
    'Local life, Về đêm, Đi bộ, Nhộn nhịp',
    1, '19:00', '24:00', 'Chỉ mở T6, T7, CN', NULL,
    'Tuyến phố quanh Hồ Gươm cấm xe vào tối cuối tuần — không khí như hội hè với âm nhạc, nhảy múa và người dân địa phương.',
    'Các con đường quanh hồ đóng cửa với xe cộ từ tối Thứ Sáu đến hết Chủ Nhật. Người dân ra chơi nhạc, các nhóm sinh viên tụ tập ca hát, nhảy múa, biểu diễn đường phố. Kết hợp hoàn hảo với Chợ đêm Phố cổ cùng khung giờ.',
    NULL, true, true
  ),
  (
    'HN', 'Hồ Hoàn Kiếm (Hồ Gươm)', 'Hoàn Kiếm',
    'Trung tâm quận Hoàn Kiếm, Hà Nội',
    'https://www.google.com/maps/search/?api=1&query=H%E1%BB%93+Ho%C3%A0n+Ki%E1%BA%BFm',
    'Danh lam thắng cảnh, Di tích',
    'Nổi tiếng, Biểu tượng, Tâm linh, Hoàng hôn',
    1, '00:00', '24:00', 'Không nghỉ', NULL,
    'Hồ nước được xem là trái tim của Hà Nội — gắn với truyền thuyết trả gươm thần và bao quanh bởi các công trình lịch sử nổi tiếng.',
    'Quanh hồ là Tháp Rùa, đền Ngọc Sơn, cầu Thê Húc và Tháp Bút. Tối Thứ Sáu đến hết Chủ Nhật các phố quanh hồ trở thành phố đi bộ sầm uất. Sáng sớm là nơi người Hà Nội tập thể dục và cảm nhận nhịp thở chậm rãi của thành phố.',
    NULL, true, true
  ),
  (
    'HN', 'Đền Ngọc Sơn & Cầu Thê Húc', 'Hoàn Kiếm',
    'Đảo Ngọc, Hồ Hoàn Kiếm, Hoàn Kiếm, Hà Nội',
    'https://www.google.com/maps/search/?api=1&query=%C4%90%E1%BB%81n+Ng%E1%BB%8Dc+S%C6%A1n',
    'Di tích tín ngưỡng, Kiến trúc',
    'Nổi tiếng, Tâm linh, Biểu tượng, Cổ kính',
    1, '07:00', '18:00', 'Không nghỉ', NULL,
    'Đền cổ trên đảo nhỏ giữa Hồ Gươm — nối với bờ hồ bằng cầu gỗ sơn đỏ biểu tượng nhất Hà Nội.',
    'Cầu Thê Húc cong cong sơn đỏ là một trong những hình ảnh được chụp nhiều nhất ở Hà Nội. Bên trong đền còn lưu giữ một mẫu vật rùa hồ Gươm — con rùa gắn với truyền thuyết hoàn kiếm. Kết hợp tham quan khi dạo quanh Hồ Gươm.',
    NULL, true, true
  ),
  (
    'HN', 'Nhà Thờ Lớn Hà Nội', 'Hoàn Kiếm',
    '40 Nhà Chung, Hàng Trống, Hoàn Kiếm, Hà Nội',
    'https://www.google.com/maps/search/?api=1&query=Nh%C3%A0+th%E1%BB%9D+L%E1%BB%9Bn+H%C3%A0+N%E1%BB%99i',
    'Kiến trúc, Tôn giáo',
    'Nổi tiếng, Kiến trúc Pháp, Gothic, Chụp ảnh',
    1, '08:00', '17:00', 'Không nghỉ', NULL,
    'Nhà thờ Công giáo kiến trúc Gothic biểu tượng kiến trúc Pháp của Hà Nội — điểm tụ tập nổi tiếng với trà chanh và các quán cà phê xung quanh.',
    'Xây cuối thế kỷ 19, Nhà thờ Lớn là công trình kiến trúc Gothic tiêu biểu nhất Hà Nội. Quảng trường trước nhà thờ và các ngõ phố Nhà Chung xung quanh là khu vực cà phê và ẩm thực sôi động, đặc biệt về buổi tối cuối tuần.',
    NULL, true, true
  ),
  (
    'HN', 'Nhà Hát Lớn Hà Nội', 'Hoàn Kiếm',
    'Số 1 Tràng Tiền, Hoàn Kiếm, Hà Nội',
    'https://www.google.com/maps/search/?api=1&query=Nh%C3%A0+h%C3%A1t+L%E1%BB%9Bn+H%C3%A0+N%E1%BB%99i',
    'Kiến trúc, Văn hóa, Nghệ thuật',
    'Nổi tiếng, Kiến trúc Pháp, Sang trọng, Cổ điển',
    2, '08:00', '22:00', 'Không nghỉ', NULL,
    'Nhà hát kiến trúc Pháp xây 1901-1911 theo mẫu Opéra Garnier Paris — nơi diễn ra nhiều sự kiện lịch sử và các buổi hòa nhạc đẳng cấp.',
    'Là nơi diễn ra nhiều sự kiện lịch sử quan trọng, nhà hát vẫn thường xuyên có các buổi hòa nhạc, ballet và biểu diễn nghệ thuật. Kiến trúc ngoại thất đặc sắc ngay cả khi không mua vé vào xem — đặc biệt đẹp khi được chiếu sáng vào buổi tối.',
    NULL, true, true
  ),
  (
    'HN', 'Chùa Một Cột', 'Ba Đình',
    'Phố Chùa Một Cột, Đội Cấn, Ba Đình, Hà Nội',
    'https://www.google.com/maps/search/?api=1&query=Ch%C3%B9a+M%E1%BB%99t+C%E1%BB%99t',
    'Di tích tín ngưỡng, Kiến trúc',
    'Nổi tiếng, Biểu tượng, Tâm linh, Kiến trúc độc đáo',
    1, '08:00', '17:00', 'Không nghỉ', NULL,
    'Ngôi chùa dựng trên một cột đá giữa hồ xây từ năm 1049 thời Lý — kiến trúc tạo hình như bông sen vươn lên từ mặt nước.',
    'Một trong những biểu tượng được nhận diện nhiều nhất của Hà Nội. Chùa nằm trong khuôn viên Khu di tích Phủ Chủ tịch nên thường tham quan kết hợp với Nhà sàn Bác Hồ và Lăng Bác cùng một buổi.',
    NULL, true, true
  ),
  (
    'HN', 'Lăng Chủ Tịch Hồ Chí Minh', 'Ba Đình',
    'Số 2 Hùng Vương, Điện Biên, Ba Đình, Hà Nội',
    'https://www.google.com/maps/search/?api=1&query=L%C4%83ng+H%E1%BB%93+Ch%C3%AD+Minh',
    'Di tích lịch sử, Trang nghiêm',
    'Nổi tiếng, Lịch sử, Trang nghiêm, Quốc gia',
    1, '07:30', '10:30', 'Thứ 2 & Thứ 6', NULL,
    'Nơi yên nghỉ của Chủ tịch Hồ Chí Minh tại Quảng trường Ba Đình — lễ thượng cờ 6h sáng mỗi ngày là nghi lễ đặc biệt.',
    'Khách viếng cần ăn mặc lịch sự, không mang thiết bị ghi hình vào bên trong. Lễ thượng cờ lúc 6h sáng và hạ cờ lúc 21h tối mỗi ngày tại Quảng trường Ba Đình là nghi lễ đáng xem. Kết hợp tham quan Nhà sàn Bác Hồ, Chùa Một Cột cùng khuôn viên.',
    NULL, true, true
  ),
  (
    'HN', 'Khu Di Tích Phủ Chủ Tịch (Nhà Sàn Bác Hồ)', 'Ba Đình',
    '1 Hoàng Hoa Thám, Ba Đình, Hà Nội',
    'https://www.google.com/maps/search/?api=1&query=Ph%E1%BB%A7+Ch%E1%BB%A7+t%E1%BB%8Bch',
    'Di tích lịch sử, Vườn',
    'Nổi tiếng, Lịch sử, Yên tĩnh, Khám phá',
    1, '08:00', '11:00', 'Không nghỉ', NULL,
    'Nhà sàn gỗ và ao cá giữa khuôn viên xanh — nơi Chủ tịch Hồ Chí Minh sống và làm việc trong những năm cuối đời.',
    'Khuôn viên rộng với nhà sàn gỗ đơn giản tương phản với Phủ Chủ tịch hoành tráng bên cạnh — thể hiện lối sống giản dị của vị lãnh tụ. Còn có Chùa Một Cột, vườn cây và ao cá trong cùng khu vực.',
    NULL, true, true
  ),
  (
    'HN', 'Hoàng Thành Thăng Long', 'Ba Đình',
    '19C Hoàng Diệu, Ba Đình, Hà Nội',
    'https://www.google.com/maps/search/?api=1&query=Ho%C3%A0ng+th%C3%A0nh+Th%C4%83ng+Long',
    'Di tích, Di sản UNESCO',
    'Nổi tiếng, Di sản, Lịch sử, Khảo cổ',
    1, '08:00', '17:00', 'Thứ 2', NULL,
    'Di tích kinh đô qua nhiều triều đại được UNESCO công nhận năm 2010 — khu khảo cổ với dấu tích cung điện và giếng cổ từ thời phong kiến.',
    'Hoàng thành Thăng Long là trung tâm chính trị của nhà nước Đại Việt qua hơn 1.000 năm. Khu khảo cổ lộ thiên tầng 18 cho thấy dấu tích cung điện, giếng cổ, chân cột trụ từ thời phong kiến chồng lên nhiều lớp. Nên dành 1,5-2 giờ để tham quan trọn vẹn.',
    NULL, true, true
  ),
  (
    'HN', 'Chùa Trấn Quốc', 'Tây Hồ',
    '52 Đặng Thai Mai, Quảng An, Tây Hồ, Hà Nội',
    'https://www.google.com/maps/search/?api=1&query=Ch%C3%B9a+Tr%E1%BA%A5n+Qu%E1%BB%91c',
    'Di tích tín ngưỡng, Thiên nhiên',
    'Nổi tiếng, Tâm linh, Cổ kính, Hoàng hôn',
    1, '08:00', '16:00', 'Không nghỉ', NULL,
    'Một trong những ngôi chùa cổ nhất Việt Nam trên đảo nhỏ ở Hồ Tây — đẹp đặc biệt vào lúc hoàng hôn nhìn từ đường Thanh Niên.',
    'Từng là trung tâm Phật giáo của kinh thành Thăng Long thời Lý - Trần. Chùa nằm trên bán đảo nhô ra Hồ Tây với khung cảnh thiên nhiên hùng vĩ. Nên ghé vào buổi chiều để cảm nhận ánh nắng hoàng hôn xuyên qua tán cây cổ thụ.',
    NULL, true, true
  ),
  (
    'HN', 'Hồ Tây (Đường Thanh Niên)', 'Tây Hồ',
    'Đường Thanh Niên, Tây Hồ, Hà Nội',
    'https://www.google.com/maps/search/?api=1&query=H%E1%BB%93+T%C3%A2y+Thanh+Ni%C3%AAn',
    'Danh lam thắng cảnh, Trải nghiệm',
    'Nổi tiếng, Thiên nhiên, Hoàng hôn, Đi bộ, Café',
    1, '00:00', '24:00', 'Không nghỉ', NULL,
    'Hồ nước ngọt lớn nhất Hà Nội — con đường Thanh Niên giữa Hồ Tây và Hồ Trúc Bạch là tuyến đi bộ ngắm cảnh và café ven hồ đẹp nhất thành phố.',
    'Đường Thanh Niên chạy giữa Hồ Tây và Hồ Trúc Bạch là tuyến đi bộ và đạp xe ngắm cảnh nổi tiếng nhất khu vực này. Dọc hai bên là các quán café ven hồ, nhà hàng và các di tích như Đền Quán Thánh, Chùa Trấn Quốc. Hoàng hôn trên Hồ Tây là một trong những cảnh đẹp biểu tượng của Hà Nội.',
    NULL, true, true
  ),
  (
    'HN', 'Nhà Tù Hỏa Lò', 'Hoàn Kiếm',
    '1 Phố Hỏa Lò, Trần Hưng Đạo, Hoàn Kiếm, Hà Nội',
    'https://www.google.com/maps/search/?api=1&query=Nh%C3%A0+t%C3%B9+H%E1%BB%8Fa+L%C3%B2',
    'Di tích lịch sử, Bảo tàng',
    'Nổi tiếng, Lịch sử, Trầm mặc, Giáo dục',
    1, '08:00', '17:00', 'Không nghỉ', NULL,
    'Nhà tù thời Pháp thuộc từng được phi công Mỹ gọi đùa là ''Hanoi Hilton'' — trưng bày tái hiện điều kiện giam giữ khắc nghiệt qua hai cuộc chiến.',
    'Tái hiện điều kiện giam giữ khắc nghiệt thời Pháp thuộc và chiến tranh Việt Nam. Là điểm đến lịch sử được nhiều khách nước ngoài, đặc biệt là người Mỹ, quan tâm. Nằm ngay trung tâm quận Hoàn Kiếm — phù hợp kết hợp trong lộ trình khám phá phố cổ.',
    NULL, true, true
  ),
  (
    'HN', 'Bảo Tàng Mỹ Thuật Việt Nam', 'Ba Đình',
    '66 Nguyễn Thái Học, Ba Đình, Hà Nội',
    'https://www.google.com/maps/search/?api=1&query=B%E1%BA%A3o+t%C3%A0ng+M%E1%BB%B9+thu%E1%BA%ADt+Vi%E1%BB%87t+Nam',
    'Bảo tàng, Nghệ thuật',
    'Nổi tiếng, Nghệ thuật, Yên tĩnh, Sâu lắng',
    1, '08:30', '17:00', 'Thứ 2', NULL,
    'Bảo tàng nghệ thuật hàng đầu lưu giữ hơn 20.000 hiện vật — tranh sơn mài, tượng và hội họa Việt Nam từ cổ đại đến đương đại.',
    'Trưng bày tranh, tượng qua các thời kỳ từ cổ đại đến đương đại trong tòa nhà cũ kiến trúc Đông Dương đặc trưng. Bộ sưu tập tranh sơn mài và tranh lụa thời kỳ Đông Dương được đánh giá rất cao trong giới mỹ thuật quốc tế.',
    NULL, true, true
  ),
  (
    'HN', 'Bảo Tàng Lịch Sử Quân Sự Việt Nam', 'Nam Từ Liêm',
    'Km 6+500 Đại lộ Thăng Long, Nam Từ Liêm, Hà Nội',
    'https://www.google.com/maps/search/?api=1&query=B%E1%BA%A3o+t%C3%A0ng+L%E1%BB%8Bch+s%E1%BB%AD+Qu%C3%A2n+s%E1%BB%B1',
    'Bảo tàng, Lịch sử',
    'Nổi tiếng, Lịch sử quân sự, Quy mô lớn',
    1, '08:00', '16:30', 'Thứ 2 & Thứ 6', NULL,
    'Bảo tàng quân sự quy mô lớn mới mở năm 2024 — lưu giữ hơn 150.000 hiện vật gồm xe tăng T-54B và máy bay MiG-21 huyền thoại.',
    'Thay thế cơ sở cũ ở 28A Điện Biên Phủ với quy mô lớn hơn nhiều. Tháp Chiến thắng cao 45m là điểm nhấn kiến trúc. Bảo vật quốc gia gồm xe tăng T-54B số 843 húc đổ cổng Dinh Độc Lập ngày 30/4/1975.',
    NULL, true, true
  ),
  (
    'HN', 'Bảo Tàng Phụ Nữ Việt Nam', 'Hoàn Kiếm',
    '36 Lý Thường Kiệt, Hoàn Kiếm, Hà Nội',
    'https://www.google.com/maps/search/?api=1&query=B%E1%BA%A3o+t%C3%A0ng+Ph%E1%BB%A5+n%E1%BB%AF+Vi%E1%BB%87t+Nam',
    'Bảo tàng, Văn hóa',
    'Nổi tiếng, Văn hóa, Giáo dục, Thân thiện',
    1, '08:00', '17:00', 'Không nghỉ', NULL,
    'Bảo tàng tôn vinh vai trò và văn hóa của phụ nữ Việt Nam — được đánh giá là một trong những bảo tàng được thiết kế hiện đại nhất Hà Nội.',
    'Trưng bày về vai trò phụ nữ trong lịch sử và văn hóa Việt Nam từ cổ đại đến hiện đại. Được thiết kế thân thiện với khách quốc tế, có thuyết minh đa ngôn ngữ. Phù hợp cho mọi đối tượng khách tham quan.',
    NULL, true, true
  ),
  (
    'HN', 'Đền Bạch Mã', 'Hoàn Kiếm',
    '76 Hàng Buồm, Hoàn Kiếm, Hà Nội',
    'https://www.google.com/maps/search/?api=1&query=%C4%90%E1%BB%81n+B%E1%BA%A1ch+M%C3%A3',
    'Di tích tín ngưỡng',
    'Nổi tiếng, Tâm linh, Tứ trấn Thăng Long, Cổ kính',
    1, '08:00', '17:00', 'Không nghỉ', NULL,
    'Một trong Tứ trấn Thăng Long — được coi là ngôi đền cổ nhất Hà Nội thờ thần Long Đỗ bảo hộ kinh thành.',
    'Đền Bạch Mã trấn giữ phía Đông của kinh thành Thăng Long xưa, cùng với Đền Quán Thánh (Bắc), Đền Voi Phục (Tây) và Đền Kim Liên (Nam) tạo thành bộ Tứ trấn. Nằm ngay trên phố Hàng Buồm trong khu phố cổ — dễ dàng kết hợp trong lộ trình tham quan phố cổ.',
    NULL, true, true
  ),
  (
    'HN', 'Phố Bia Hơi Tạ Hiện', 'Hoàn Kiếm',
    'Ngã tư Tạ Hiện - Lương Ngọc Quyến, Hoàn Kiếm, Hà Nội',
    'https://www.google.com/maps/search/?api=1&query=ph%E1%BB%91+T%E1%BA%A1+Hi%E1%BB%87n',
    'Ẩm thực, Về đêm',
    'Nổi tiếng, Local life, Nightlife, Đường phố, Vui vẻ',
    1, '17:00', '02:00', 'Không nghỉ', NULL,
    'Góc phố nổi tiếng với biệt danh phố Tây — ngồi ghế nhựa vỉa hè nhâm nhi bia hơi và đồ nhắm đường phố cùng người địa phương.',
    'Là một trong những điểm tụ tập về đêm nổi tiếng nhất với khách du lịch quốc tế. Bia hơi Hà Nội giá chỉ 15-25k/cốc, kèm đồ nhắm vỉa hè đa dạng. Không khí náo nhiệt, thân thiện — trải nghiệm đặc trưng của văn hóa bia hơi Hà Nội.',
    NULL, true, true
  ),
  (
    'HN', 'Chùa Hương', 'Mỹ Đức',
    'Xã Hương Sơn, Mỹ Đức, Hà Nội',
    'https://www.google.com/maps/search/?api=1&query=Ch%C3%B9a+H%C6%B0%C6%A1ng',
    'Di tích tín ngưỡng, Thiên nhiên',
    'Nổi tiếng, Tâm linh, Thiên nhiên, Lễ hội',
    2, '06:00', '17:00', 'Không nghỉ', NULL,
    'Quần thể chùa chiền nổi tiếng — đi thuyền qua suối Yến vào động Hương Tích là hành trình khó quên giữa núi non hùng vĩ.',
    'Lễ hội chùa Hương đầu năm (tháng Giêng đến tháng 3 âm lịch) thu hút lượng khách rất lớn — nên đi sớm để tránh đông đúc. Hành trình gồm đi thuyền trên suối Yến, cáp treo hoặc leo bộ vào động Hương Tích. Nên dành cả ngày cho chuyến đi.',
    NULL, true, true
  ),
  (
    'HN', 'Chùa Thầy', 'Quốc Oai',
    'Xã Sài Sơn, Quốc Oai, Hà Nội',
    'https://www.google.com/maps/search/?api=1&query=Ch%C3%B9a+Th%E1%BA%A7y',
    'Di tích tín ngưỡng, Thiên nhiên',
    'Nổi tiếng, Tâm linh, Kiến trúc, Yên tĩnh',
    1, '07:00', '18:00', 'Không nghỉ', NULL,
    'Chùa cổ dưới chân núi Sài Sơn gắn với Thiền sư Từ Đạo Hạnh — quần thể đẹp với cầu đá cổ bắc qua hồ và hang động bí ẩn.',
    'Quần thể gồm chùa, hang động và cầu Nhật Tiên - Nguyệt Tiên bắc qua hồ trước chùa. Lễ hội chùa Thầy diễn ra vào tháng 3 âm lịch. Có thể kết hợp tham quan với làng chuồn chuồn tre Thạch Xá và Chùa Tây Phương gần đó.',
    NULL, true, true
  ),
  (
    'HN', 'Chùa Tây Phương', 'Thạch Thất',
    'Xã Thạch Xá, Thạch Thất, Hà Nội',
    'https://www.google.com/maps/search/?api=1&query=Ch%C3%B9a+T%C3%A2y+Ph%C6%B0%C6%A1ng',
    'Di tích tín ngưỡng, Nghệ thuật',
    'Nổi tiếng, Tâm linh, Nghệ thuật điêu khắc, Yên tĩnh',
    1, '07:00', '18:00', 'Không nghỉ', NULL,
    'Chùa cổ trên núi với hệ thống tượng La Hán bằng gỗ được coi là đỉnh cao của nghệ thuật điêu khắc gỗ Việt Nam.',
    'Các tượng La Hán ở đây đã đi vào thơ của Huy Cận và được giới chuyên môn đánh giá là kiệt tác điêu khắc. Chùa nằm trên núi Câu Lậu phải leo bậc thang đá để lên — khung cảnh thiên nhiên xanh mát và tĩnh lặng.',
    NULL, true, true
  ),
  (
    'HN', 'Vườn Quốc Gia Ba Vì', 'Ba Vì',
    'Xã Tản Lĩnh, Ba Vì, Hà Nội',
    'https://www.google.com/maps/search/?api=1&query=V%C6%B0%E1%BB%9Dn+qu%E1%BB%91c+gia+Ba+V%C3%AC',
    'Thiên nhiên, Trải nghiệm',
    'Nổi tiếng, Thiên nhiên, Leo núi, Khí hậu mát',
    1, '07:00', '17:00', 'Không nghỉ', NULL,
    'Vườn quốc gia với rừng núi và khí hậu mát mẻ cách trung tâm 50km — có đỉnh Vua và các công trình nghỉ dưỡng cổ thời Pháp còn sót lại trên núi.',
    'Có thể leo lên đỉnh Vua (1.296m), tham quan vườn thảo dược và các biệt thự Pháp hoang tàn trên sườn núi. Khí hậu mát mẻ quanh năm, đặc biệt phù hợp vào mùa hè khi Hà Nội nóng bức. Nên dành cả ngày cho chuyến đi.',
    NULL, true, true
  ),
  (
    'HN', 'Thành Cổ Loa', 'Đông Anh',
    'Xã Cổ Loa, Đông Anh, Hà Nội',
    'https://www.google.com/maps/search/?api=1&query=Th%C3%A0nh+C%E1%BB%95+Loa',
    'Di tích lịch sử, Khảo cổ',
    'Nổi tiếng, Lịch sử, Truyền thuyết, Khám phá',
    1, '07:00', '17:30', 'Không nghỉ', NULL,
    'Kinh đô của nhà nước Âu Lạc thời An Dương Vương — gắn với truyền thuyết Mỵ Châu - Trọng Thủy và những lớp thành đất cổ độc đáo.',
    'Di tích còn lưu giữ các lớp thành đất cổ hình xoắn ốc và đền thờ An Dương Vương. Lễ hội Cổ Loa diễn ra đầu năm âm lịch với nhiều nghi thức truyền thống. Cách trung tâm Hà Nội khoảng 17km.',
    NULL, true, true
  );
