-- Seed coordinates for Hanoi (HN) locations
UPDATE locations SET coordinates = '{"lat": 21.0297, "lng": 105.8539}'::jsonb WHERE city = 'HN' AND name = 'Nhà Hát Múa Rối Thăng Long';
UPDATE locations SET coordinates = '{"lat": 21.0336, "lng": 105.8498}'::jsonb WHERE city = 'HN' AND name = 'Trung Tâm Văn Hóa Nghệ Thuật 22 Hàng Buồm';
UPDATE locations SET coordinates = '{"lat": 21.0376, "lng": 105.7971}'::jsonb WHERE city = 'HN' AND name = 'Bảo Tàng Dân Tộc Học Việt Nam';
UPDATE locations SET coordinates = '{"lat": 20.7233, "lng": 105.8340}'::jsonb WHERE city = 'HN' AND name = 'Làng Nghề Tăm Hương Quảng Phú Cầu';
UPDATE locations SET coordinates = '{"lat": 21.0338, "lng": 105.8374}'::jsonb WHERE city = 'HN' AND name = 'Cột Cờ Hà Nội (Kỳ Đài)';
UPDATE locations SET coordinates = '{"lat": 21.0005, "lng": 105.9100}'::jsonb WHERE city = 'HN' AND name = 'Bảo Tàng Gốm Bát Tràng';
UPDATE locations SET coordinates = '{"lat": 20.9700, "lng": 105.7742}'::jsonb WHERE city = 'HN' AND name = 'Đình Vạn Phúc & Con Đường Ô';
UPDATE locations SET coordinates = '{"lat": 21.1340, "lng": 105.4950}'::jsonb WHERE city = 'HN' AND name = 'Làng Cổ Đường Lâm (Đình Mông Phụ & Nhà Cổ)';
UPDATE locations SET coordinates = '{"lat": 21.0447, "lng": 105.8626}'::jsonb WHERE city = 'HN' AND name = 'Cầu Long Biên';
UPDATE locations SET coordinates = '{"lat": 21.0391, "lng": 105.8556}'::jsonb WHERE city = 'HN' AND name = 'Dự Án Nghệ Thuật Công Cộng Phúc Tân';
UPDATE locations SET coordinates = '{"lat": 21.0362, "lng": 105.8497}'::jsonb WHERE city = 'HN' AND name = 'Chợ Đồng Xuân';
UPDATE locations SET coordinates = '{"lat": 21.0360, "lng": 105.8470}'::jsonb WHERE city = 'HN' AND name = 'Chợ Đêm Phố Cổ (Hàng Đào - Đồng Xuân)';
UPDATE locations SET coordinates = '{"lat": 21.0432, "lng": 105.8367}'::jsonb WHERE city = 'HN' AND name = 'Đền Quán Thánh';
UPDATE locations SET coordinates = '{"lat": 21.0339, "lng": 105.8521}'::jsonb WHERE city = 'HN' AND name = 'Hanoi Ca Trù Club (Đền Kim Ngân)';
UPDATE locations SET coordinates = '{"lat": 21.0348, "lng": 105.8532}'::jsonb WHERE city = 'HN' AND name = 'Ô Quan Chưởng';
UPDATE locations SET coordinates = '{"lat": 21.0268, "lng": 105.8359}'::jsonb WHERE city = 'HN' AND name = 'Văn Miếu - Quốc Tử Giám';
UPDATE locations SET coordinates = '{"lat": 21.0285, "lng": 105.8524}'::jsonb WHERE city = 'HN' AND name = 'Phố Đi Bộ Hồ Hoàn Kiếm';
UPDATE locations SET coordinates = '{"lat": 21.0285, "lng": 105.8524}'::jsonb WHERE city = 'HN' AND name = 'Hồ Hoàn Kiếm (Hồ Gươm)';
UPDATE locations SET coordinates = '{"lat": 21.0296, "lng": 105.8524}'::jsonb WHERE city = 'HN' AND name = 'Đền Ngọc Sơn & Cầu Thê Húc';
UPDATE locations SET coordinates = '{"lat": 21.0277, "lng": 105.8491}'::jsonb WHERE city = 'HN' AND name = 'Nhà Thờ Lớn Hà Nội';
UPDATE locations SET coordinates = '{"lat": 21.0255, "lng": 105.8571}'::jsonb WHERE city = 'HN' AND name = 'Nhà Hát Lớn Hà Nội';
UPDATE locations SET coordinates = '{"lat": 21.0357, "lng": 105.8353}'::jsonb WHERE city = 'HN' AND name = 'Chùa Một Cột';
UPDATE locations SET coordinates = '{"lat": 21.0371, "lng": 105.8347}'::jsonb WHERE city = 'HN' AND name = 'Lăng Chủ Tịch Hồ Chí Minh';
UPDATE locations SET coordinates = '{"lat": 21.0393, "lng": 105.8372}'::jsonb WHERE city = 'HN' AND name = 'Khu Di Tích Phủ Chủ Tịch (Nhà Sàn Bác Hồ)';
UPDATE locations SET coordinates = '{"lat": 21.0355, "lng": 105.8355}'::jsonb WHERE city = 'HN' AND name = 'Hoàng Thành Thăng Long';
UPDATE locations SET coordinates = '{"lat": 21.0482, "lng": 105.8327}'::jsonb WHERE city = 'HN' AND name = 'Chùa Trấn Quốc';
UPDATE locations SET coordinates = '{"lat": 21.0573, "lng": 105.8246}'::jsonb WHERE city = 'HN' AND name = 'Hồ Tây (Đường Thanh Niên)';
UPDATE locations SET coordinates = '{"lat": 21.0253, "lng": 105.8468}'::jsonb WHERE city = 'HN' AND name = 'Nhà Tù Hỏa Lò';
UPDATE locations SET coordinates = '{"lat": 21.0295, "lng": 105.8391}'::jsonb WHERE city = 'HN' AND name = 'Bảo Tàng Mỹ Thuật Việt Nam';
UPDATE locations SET coordinates = '{"lat": 21.0117, "lng": 105.7669}'::jsonb WHERE city = 'HN' AND name = 'Bảo Tàng Lịch Sử Quân Sự Việt Nam';
UPDATE locations SET coordinates = '{"lat": 21.0225, "lng": 105.8513}'::jsonb WHERE city = 'HN' AND name = 'Bảo Tàng Phụ Nữ Việt Nam';
UPDATE locations SET coordinates = '{"lat": 21.0343, "lng": 105.8503}'::jsonb WHERE city = 'HN' AND name = 'Đền Bạch Mã';
UPDATE locations SET coordinates = '{"lat": 21.0349, "lng": 105.8529}'::jsonb WHERE city = 'HN' AND name = 'Phố Bia Hơi Tạ Hiện';
UPDATE locations SET coordinates = '{"lat": 20.6197, "lng": 105.7592}'::jsonb WHERE city = 'HN' AND name = 'Chùa Hương';
UPDATE locations SET coordinates = '{"lat": 20.9603, "lng": 105.6911}'::jsonb WHERE city = 'HN' AND name = 'Chùa Thầy';
UPDATE locations SET coordinates = '{"lat": 20.9617, "lng": 105.6542}'::jsonb WHERE city = 'HN' AND name = 'Chùa Tây Phương';
UPDATE locations SET coordinates = '{"lat": 21.0625, "lng": 105.3503}'::jsonb WHERE city = 'HN' AND name = 'Vườn Quốc Gia Ba Vì';
UPDATE locations SET coordinates = '{"lat": 21.1054, "lng": 105.8808}'::jsonb WHERE city = 'HN' AND name = 'Thành Cổ Loa';
