-- Seed coordinates for Da Nang / Hoi An (DN) locations
UPDATE locations SET coordinates = '{"lat": 16.1285, "lng": 107.9547}'::jsonb WHERE city = 'DN' AND name = 'Trung Tâm Văn Hóa Du Lịch Cộng Đồng Tà Lang - Giàn Bí';
UPDATE locations SET coordinates = '{"lat": 15.9152, "lng": 108.3092}'::jsonb WHERE city = 'DN' AND name = 'The Hang Art';
UPDATE locations SET coordinates = '{"lat": 16.0044, "lng": 108.0856}'::jsonb WHERE city = 'DN' AND name = 'Làng Toom Sara';
UPDATE locations SET coordinates = '{"lat": 15.8784, "lng": 108.3293}'::jsonb WHERE city = 'DN' AND name = 'Gióng Café';
UPDATE locations SET coordinates = '{"lat": 16.0683, "lng": 108.2244}'::jsonb WHERE city = 'DN' AND name = 'Bảo Tàng Điêu Khắc Chăm';
UPDATE locations SET coordinates = '{"lat": 15.8790, "lng": 108.3274}'::jsonb WHERE city = 'DN' AND name = 'Laque Restaurant & Coffee';
UPDATE locations SET coordinates = '{"lat": 15.8956, "lng": 108.2995}'::jsonb WHERE city = 'DN' AND name = 'Làng Củi Lũ Hội An (Driftwood Village)';
UPDATE locations SET coordinates = '{"lat": 16.0668, "lng": 108.2109}'::jsonb WHERE city = 'DN' AND name = 'Bar Đồ Yêu - Authentic Vietnamese Cocktail';
UPDATE locations SET coordinates = '{"lat": 16.1290, "lng": 107.9550}'::jsonb WHERE city = 'DN' AND name = 'Homestay Alang Nhu';
UPDATE locations SET coordinates = '{"lat": 16.0564, "lng": 108.2323}'::jsonb WHERE city = 'DN' AND name = 'The Heritage Show';
UPDATE locations SET coordinates = '{"lat": 15.8849, "lng": 108.3005}'::jsonb WHERE city = 'DN' AND name = 'Công Viên Đất Nung Thanh Hà';
UPDATE locations SET coordinates = '{"lat": 15.9995, "lng": 107.9875}'::jsonb WHERE city = 'DN' AND name = 'Ba Na Hills';
UPDATE locations SET coordinates = '{"lat": 15.8724, "lng": 108.3246}'::jsonb WHERE city = 'DN' AND name = 'Làng Mộc Kim Bồng';
UPDATE locations SET coordinates = '{"lat": 15.8870, "lng": 108.3247}'::jsonb WHERE city = 'DN' AND name = 'EVERY HALF';
UPDATE locations SET coordinates = '{"lat": 15.8677, "lng": 108.3616}'::jsonb WHERE city = 'DN' AND name = 'Rừng Dừa Bảy Mẫu';
UPDATE locations SET coordinates = '{"lat": 15.9987, "lng": 108.2589}'::jsonb WHERE city = 'DN' AND name = 'Ngon Phố Đà';
UPDATE locations SET coordinates = '{"lat": 15.8826, "lng": 108.3291}'::jsonb WHERE city = 'DN' AND name = 'Ký Ức Hội An';
UPDATE locations SET coordinates = '{"lat": 16.0361, "lng": 108.2287}'::jsonb WHERE city = 'DN' AND name = 'Hàng Gánh';
UPDATE locations SET coordinates = '{"lat": 16.0744, "lng": 108.2104}'::jsonb WHERE city = 'DN' AND name = 'Nhà Hàng Café Trúc Lâm Viên';
UPDATE locations SET coordinates = '{"lat": 15.8765, "lng": 107.7235}'::jsonb WHERE city = 'DN' AND name = 'Cổng Trời Đông Giang';
UPDATE locations SET coordinates = '{"lat": 15.9927, "lng": 108.2618}'::jsonb WHERE city = 'DN' AND name = 'Ngon Thị Hoa Restaurant';
UPDATE locations SET coordinates = '{"lat": 16.0480, "lng": 108.2323}'::jsonb WHERE city = 'DN' AND name = 'Bếp Cuốn';
UPDATE locations SET coordinates = '{"lat": 15.8802, "lng": 108.3272}'::jsonb WHERE city = 'DN' AND name = 'Bảo Tàng Văn Hóa Sa Huỳnh';
UPDATE locations SET coordinates = '{"lat": 15.8935, "lng": 108.3518}'::jsonb WHERE city = 'DN' AND name = 'Làng Rau Trà Quế';
UPDATE locations SET coordinates = '{"lat": 15.8781, "lng": 108.3290}'::jsonb WHERE city = 'DN' AND name = 'Nhà Cổ Tân Kỳ';
UPDATE locations SET coordinates = '{"lat": 16.1050, "lng": 108.0050}'::jsonb WHERE city = 'DN' AND name = 'Leaf Village & Farm';
UPDATE locations SET coordinates = '{"lat": 15.9808, "lng": 107.9900}'::jsonb WHERE city = 'DN' AND name = 'The Farmers';
UPDATE locations SET coordinates = '{"lat": 15.8787, "lng": 108.3263}'::jsonb WHERE city = 'DN' AND name = 'Hội Quán Phước Kiến';
UPDATE locations SET coordinates = '{"lat": 16.1138, "lng": 108.2656}'::jsonb WHERE city = 'DN' AND name = 'Bảo Tàng Đồng Đình';
UPDATE locations SET coordinates = '{"lat": 16.0023, "lng": 108.2560}'::jsonb WHERE city = 'DN' AND name = 'Nhà Gỗ Villa';
