-- Seed: Da Nang + Hoi An (DN) locations
INSERT INTO locations (city, name, district, address, google_maps_url, category, style_tag, price_level, opening_hours, closing_hours, off_days, phone, short_description, long_description, photos, verified, is_active)
VALUES
  (
    'DN', 'Trung Tâm Văn Hóa Du Lịch Cộng Đồng Tà Lang - Giàn Bí', 'Hải Vân',
    'Xã Hòa Bắc, Hải Vân, Đà Nẵng',
    'https://maps.app.goo.gl/rheznref68Bvizyr7',
    'Trải nghiệm, Du lịch cộng đồng',
    'Yên bình, Bản địa, Thư giãn',
    1, '00:00', '24:00', 'Không nghỉ', '+84 90 539 8892',
    'Du lịch cộng đồng kết hợp trải nghiệm văn hoá và thiên nhiên đặc trưng miền núi Đà Nẵng.',
    'Khám phá Trung tâm Văn hóa du lịch cộng đồng Tà Lang - Giàn Bí — điểm đến độc đáo ở Hòa Bắc. Trải nghiệm cắm trại và ẩm thực địa phương giữa không gian núi rừng đặc trưng miền Tây Đà Nẵng.',
    NULL, true, true
  ),
  (
    'DN', 'The Hang Art', 'Điện Bàn',
    'Lạc Long Quân, Điện Bàn, Quảng Nam',
    'https://maps.app.goo.gl/wwqv3UJdeVnC2qfz7',
    'Check-in, Workshop, Café',
    'Nghệ thuật đương đại, Workshop thủ công, Kiến trúc tối giản, Văn hóa Việt',
    2, '07:00', '20:00', 'Không nghỉ', '+84 86 641 1579',
    'Nơi di sản giao thoa nghệ thuật — không gian nghệ thuật đương đại kết hợp với 12 workshop thủ công truyền thống.',
    'Khám phá workshop tại Lạc Long Quân — địa điểm check-in mới lạ kết hợp không gian nghệ thuật và workshop thủ công. Các hoạt động gồm làm hạt nhựa ủi, nghệ thuật thủ công và cà phê sáng tạo trong không gian kiến trúc tối giản.',
    NULL, true, true
  ),
  (
    'DN', 'Làng Toom Sara', 'Hòa Vang',
    'Thôn Phú Túc, Hòa Vang, Đà Nẵng',
    'https://maps.app.goo.gl/uXiaSt7jxmgpNENq6',
    'Du lịch cộng đồng, Lưu trú, Trekking',
    'Du lịch cộng đồng, Văn hóa Cơ Tu, Thiên nhiên, Nghỉ dưỡng',
    2, '07:00', '22:00', 'Không nghỉ', '+84 91 922 4455',
    'Khu du lịch cộng đồng mang đậm bản sắc dân tộc Cơ Tu — kết hợp trải nghiệm văn hoá bản địa với không gian suối rừng và nghỉ dưỡng gần gũi thiên nhiên.',
    'Làng Toom Sara tại Hòa Vang mang đến trải nghiệm văn hóa độc đáo với kiến trúc truyền thống Cơ Tu, ẩm thực địa phương và nhịp sống chậm giữa núi rừng. Các hoạt động gồm trekking, BBQ và cắm trại. Nhận phòng từ 14:00 — trả phòng 10:00 hôm sau.',
    NULL, true, true
  ),
  (
    'DN', 'Gióng Café', 'Hội An',
    '9 Nguyễn Thái Học, Phố cổ, Hội An, Quảng Nam',
    'https://maps.app.goo.gl/Pp6Dg52JFefPPEyk7',
    'Café, Trải nghiệm',
    'Văn hóa Hội An, Mộc mạc, Thư giãn, Rang xay thủ công',
    1, '07:00', '21:00', 'Không nghỉ', '+84 235 377 7109',
    'Gióng Café — không gian cà phê rang xay thủ công đậm văn hoá phố Hội với trải nghiệm pha chế trực tiếp.',
    'Khám phá không gian đậm văn hoá của phố Hội thông qua việc cùng Gióng rang và pha cà phê Việt chất lượng. Không gian mộc mạc gần gũi nằm ngay trên con phố chính của Phố cổ Hội An.',
    NULL, true, true
  ),
  (
    'DN', 'Bảo Tàng Điêu Khắc Chăm', 'Hải Châu',
    'Đường 2 Tháng 9, Hải Châu, Đà Nẵng',
    'https://maps.app.goo.gl/vkv56YPicP7UgT7y9',
    'Tham quan, Trải nghiệm',
    'Văn minh Chămpa, Điêu khắc, Lịch sử, Giáo dục',
    1, '07:00', '17:00', 'Không nghỉ', '+84 236 357 2935',
    'Bảo tàng lưu giữ và trưng bày các hiện vật nghệ thuật của nền văn minh Chămpa — trải nghiệm khám phá lịch sử và di sản độc đáo tại Đà Nẵng.',
    NULL,
    NULL, true, true
  ),
  (
    'DN', 'Laque Restaurant & Coffee', 'Hội An',
    '100 Trần Phú, Phố cổ, Hội An, Quảng Nam',
    'https://maps.app.goo.gl/MQ6nJ4z1n4kQ4avv8',
    'Ẩm thực, Café',
    'Văn hóa Hội An, Đương đại, Rooftop, Triển lãm',
    2, '09:00', '22:00', 'Không nghỉ', '+84 93 191 9956',
    'Nhà hàng & cà phê giao thoa giữa văn hoá Hội An truyền thống và không gian đương đại — nổi bật với kiến trúc gỗ và rooftop nhìn xuống phố cổ.',
    'Đến với Laque Bistro để thả mình thư giãn bên ly cà phê hoặc một bữa ăn nhẹ giữa không gian yên bình và thoáng đãng. Rooftop nhìn ra phố cổ Hội An là điểm nhấn khó quên.',
    NULL, true, true
  ),
  (
    'DN', 'Làng Củi Lũ Hội An (Driftwood Village)', 'Hội An',
    'Tổ 13 Thôn Đồng Nà, Hội An Tây, Quảng Nam',
    'https://maps.app.goo.gl/ZtxXzH5sK6XKr1U58',
    'Trải nghiệm, Workshop',
    'Văn hóa địa phương, Nghệ thuật tái chế, Thủ công, Bền vững',
    1, '07:00', '17:00', 'Không nghỉ', '+84 89 922 5969',
    'Không gian nghệ thuật và thủ công tái chế từ những khúc gỗ trôi dạt sau mùa lũ — khám phá văn hoá địa phương và sáng tạo thủ công theo cách bền vững.',
    'Nơi cất giữ những nốt trầm an nhiên của thời gian. Không gian nghệ thuật làm từ gỗ củi lũ sau mùa mưa — du khách khám phá và tham gia workshop thủ công trong khung cảnh thiên nhiên yên bình ven Hội An.',
    NULL, true, true
  ),
  (
    'DN', 'Bar Đồ Yêu - Authentic Vietnamese Cocktail', 'Hải Châu',
    '87 Hoàng Văn Thụ, Hải Châu, Đà Nẵng',
    'https://maps.app.goo.gl/NeGxLu7mrvot5jPP9',
    'Trải nghiệm, Về đêm',
    'Văn hóa nghệ thuật, Cocktail Việt, Rooftop, Nightlife',
    2, '18:00', '01:00', 'Không nghỉ', '+84 77 446 8881',
    'Không gian cocktail mang tinh thần Việt — kết hợp nghệ thuật, âm nhạc và hương vị địa phương trong rooftop bar ấm cúng giữa lòng thành phố biển.',
    'Tụ điểm văn hóa nghệ thuật của các bạn trẻ yêu văn hoá đương đại giữa Đà Nẵng. Cocktail lấy cảm hứng từ hương liệu Việt Nam trong không gian nghệ thuật độc đáo.',
    NULL, true, true
  ),
  (
    'DN', 'Homestay Alang Nhu', 'Hải Vân',
    'Làng Giàn Bí, Xã Hòa Bắc, Hải Vân, Đà Nẵng',
    'https://maps.app.goo.gl/bpkgdgiakGXoKfUNA',
    'Lưu trú, Du lịch cộng đồng',
    'Sinh thái, Văn hóa Cơ Tu, Gần gũi thiên nhiên, Bản địa',
    3, '14:00', '12:00', 'Không nghỉ', '+84 91 968 6930',
    'Homestay cộng đồng tại làng Giàn Bí — lưu trú mộc mạc gần gũi thiên nhiên và văn hoá bản địa ven núi Hòa Bắc.',
    'Homestay gắn với đời sống cộng đồng địa phương giữa không gian núi rừng Hòa Bắc. Du khách tận hưởng nhịp sống chậm, khám phá văn hoá bản địa và thư giãn trong khung cảnh yên bình. Không gian lưu trú mộc mạc tạo cảm giác kết nối với môi trường và con người địa phương.',
    NULL, true, true
  ),
  (
    'DN', 'The Heritage Show', 'An Hải',
    '2 Vũ Văn Dũng, An Hải, Đà Nẵng',
    'https://maps.app.goo.gl/uiEgJ4KTy2eNgeNcA',
    'Nghệ thuật biểu diễn, Trải nghiệm',
    'Biểu diễn, Di sản miền Trung, Nghệ thuật đương đại, Âm nhạc',
    3, '17:00', '21:00', 'Không nghỉ', '+84 82 425 2168',
    'Chương trình nghệ thuật tái hiện hành trình di sản miền Trung qua âm nhạc, múa và sân khấu tương tác — đưa khán giả khám phá văn hoá Huế - Champa - Hội An trong 60 phút.',
    'Một đêm nghệ thuật tái hiện văn hoá, âm nhạc và tinh thần miền Trung theo cách đầy cảm xúc. Đến để nghe di sản kể chuyện bằng ánh sáng, sân khấu và những khoảnh khắc rất Việt. Suất diễn cố định mỗi ngày từ 19:45-20:45.',
    NULL, true, true
  ),
  (
    'DN', 'Công Viên Đất Nung Thanh Hà', 'Hội An',
    'Khối Nam Diêu, Duy Tân, Hội An Tây, Quảng Nam',
    'https://maps.app.goo.gl/rqky3HeH88JWKkF97',
    'Trải nghiệm, Văn hóa',
    'Thủ công truyền thống, Gốm đất nung, Nghệ thuật, Làng nghề',
    1, '08:00', '17:30', 'Không nghỉ', '+84 235 396 3888',
    'Không gian văn hoá - nghệ thuật tái hiện di sản gốm truyền thống Hội An — khám phá kiến trúc đất nung và trải nghiệm làm gốm thủ công.',
    'Công viên đất nung Hội An như một thế giới thu nhỏ trưng bày đời sống văn hóa và nghề gốm truyền thống. Từ đất cát bên dòng Thu Bồn, người thợ tạo nên những bức tượng mang ký ức lao động hơn 500 năm qua bàn xoay thủ công. Vẻ đẹp mộc mạc, chân phương — đất mẹ được thổi hồn để trở thành cầu nối giữa quá khứ và hiện tại.',
    NULL, true, true
  ),
  (
    'DN', 'Ba Na Hills', 'Hòa Vang',
    'Thôn An Sơn, Hòa Vang, Đà Nẵng',
    'https://maps.app.goo.gl/gdxu9FzmoBj2Bi5z5',
    'Trải nghiệm, Check-in, Giải trí',
    'Đặc trưng Đà Nẵng, Cáp treo, Kiến trúc châu Âu, Cầu Vàng',
    4, '08:00', '22:00', 'Không nghỉ', NULL,
    'Khu du lịch trên núi kết hợp cảnh quan thiên nhiên và kiến trúc châu Âu — nổi bật với Cầu Vàng biểu tượng và hệ thống cáp treo dài nhất thế giới.',
    'Sun World Ba Na Hills nằm ở độ cao 1.487m, kết hợp cảnh quan thiên nhiên với Làng Pháp mang cảm hứng châu Âu, khu vui chơi trong nhà và các lễ hội nghệ thuật theo mùa. Vé vào cổng + cáp treo từ 1.000.000đ/người lớn. Nên đặt vé trước và kiểm tra lịch thời tiết.',
    NULL, true, true
  ),
  (
    'DN', 'Làng Mộc Kim Bồng', 'Hội An',
    'Thôn Trung Hà, Xã Cẩm Kim, Hội An, Quảng Nam',
    'https://maps.app.goo.gl/gFbhVB7q1sFqSoXx6',
    'Trải nghiệm, Làng nghề',
    'Thủ công truyền thống, Chạm khắc gỗ, Làng nghề, Di sản',
    1, '08:00', '17:00', 'Không nghỉ', NULL,
    'Làng nghề mộc truyền thống lâu đời bên sông Thu Bồn — nơi du khách khám phá nghệ thuật chạm khắc gỗ gắn với lịch sử xây dựng phố cổ Hội An từ thế kỷ XVI-XVII.',
    'Làng mộc Kim Bồng từng góp phần xây dựng nhiều công trình kiến trúc cổ tại Hội An và miền Trung. Du khách quan sát quy trình làm mộc truyền thống và gặp gỡ nghệ nhân địa phương trong không gian làng yên bình mộc mạc ven sông.',
    NULL, true, true
  ),
  (
    'DN', 'EVERY HALF', 'Hội An',
    '28 Nguyễn Tất Thành, Hội An Tây, Quảng Nam',
    'https://maps.app.goo.gl/48aWLNScFBz1vYK28',
    'Café, Check-in',
    'Specialty coffee, Tối giản, Yên tĩnh, Văn hóa cà phê Việt',
    1, '07:00', '20:30', 'Không nghỉ', '+84 83 899 9036',
    'Specialty coffee kết hợp văn hoá cà phê Việt và thiết kế tối giản — thưởng thức cà phê rang xay thủ công trong không gian yên tĩnh giữa Hội An.',
    NULL,
    NULL, true, true
  ),
  (
    'DN', 'Rừng Dừa Bảy Mẫu', 'Hội An',
    'Tổ 2, Thôn Cần Nhân, Xã Cẩm Thanh, Hội An, Quảng Nam',
    'https://maps.app.goo.gl/MdRymLfASQh3qPeR7',
    'Du lịch sinh thái, Trải nghiệm',
    'Sinh thái sông nước, Thuyền thúng, Rừng dừa, Địa phương',
    2, '07:30', '17:30', 'Không nghỉ', '+84 98 540 2302',
    'Khu du lịch sinh thái nổi tiếng tại Hội An — trải nghiệm chèo thuyền thúng và khám phá rừng dừa nước trong đời sống văn hoá sông nước địa phương.',
    NULL,
    NULL, true, true
  ),
  (
    'DN', 'Ngon Phố Đà', 'Ngũ Hành Sơn',
    '300 Võ Nguyên Giáp, Ngũ Hành Sơn, Đà Nẵng',
    'https://maps.app.goo.gl/KU1RfuoN2ENLAbwX6',
    'Ẩm thực',
    'Yên tĩnh, Ẩm thực miền Trung, Gần biển',
    2, '10:00', '22:00', 'Không nghỉ', '+84 91 169 4669',
    'Nhà hàng ẩm thực Việt phong cách ấm cúng — kết hợp hương vị miền Trung với không gian hiện đại gần biển Ngũ Hành Sơn.',
    NULL,
    NULL, true, true
  ),
  (
    'DN', 'Ký Ức Hội An', 'Hội An',
    '200 Nguyễn Tri Phương, Hội An, Quảng Nam',
    'https://maps.app.goo.gl/FHnJzgWJq8hc8wZf7',
    'Nghệ thuật biểu diễn, Trải nghiệm',
    'Show thực cảnh, Di sản văn hóa, Nghệ thuật quy mô lớn, Ánh sáng',
    3, '16:00', '22:00', 'Thứ 3', NULL,
    'Show diễn thực cảnh ngoài trời tái hiện hơn 400 năm lịch sử và văn hoá Hội An — âm nhạc, ánh sáng, múa và hàng trăm diễn viên.',
    'Ký Ức Hội An đưa du khách bước vào văn hoá thương cảng Hội An qua nhiều thời kỳ bằng hình thức biểu diễn thực cảnh ngoài trời. Show chính từ 20:00-21:00, trước đó khu Công viên Ấn Tượng mở cửa từ 16:00 với mini show và không gian tham quan nghệ thuật.',
    NULL, true, true
  ),
  (
    'DN', 'Hàng Gánh', 'Ngũ Hành Sơn',
    '51 Trần Bạch Đằng, Ngũ Hành Sơn, Đà Nẵng',
    'https://maps.app.goo.gl/jd7bAto3BEsJGrEv6',
    'Ẩm thực',
    'Ẩm thực truyền thống, Văn hóa gánh hàng, Mộc mạc',
    2, '07:00', '23:00', 'Không nghỉ', '+84 91 680 8562',
    'Nhà hàng lấy cảm hứng từ văn hoá gánh hàng Việt Nam — phục vụ ẩm thực truyền thống trong không gian mộc mạc kết hợp trải nghiệm địa phương.',
    NULL,
    NULL, true, true
  ),
  (
    'DN', 'Nhà Hàng Café Trúc Lâm Viên', 'Hải Châu',
    '08 Trần Quý Cáp, Hải Châu, Đà Nẵng',
    'https://maps.app.goo.gl/uMmCgXstfedX7y8TA',
    'Ẩm thực, Café',
    'Kiến trúc Huế, Nhà rường cổ, Sân vườn, Cổ kính',
    2, '06:30', '21:30', 'Không nghỉ', '+84 236 384 9969',
    'Nhà hàng sân vườn phong cách kiến trúc Huế truyền thống — không gian nhà rường cổ kết hợp trải nghiệm ẩm thực Việt giữa trung tâm Đà Nẵng.',
    NULL,
    NULL, true, true
  ),
  (
    'DN', 'Cổng Trời Đông Giang', 'Đông Giang',
    'Bến Hiên, Đông Giang, Quảng Nam',
    'https://maps.app.goo.gl/dsyvKEuQypSw2V177',
    'Trải nghiệm, Du lịch sinh thái',
    'Sinh thái núi rừng, Văn hóa Cơ Tu, Cáp treo, Cầu kính',
    3, '08:00', '17:00', 'Không nghỉ', '+84 93 497 3333',
    'Khu du lịch sinh thái giữa núi rừng Đông Giang — kết hợp cảnh quan thiên nhiên, hang động và trải nghiệm văn hoá Cơ Tu. Vé từ 300.000đ/người lớn.',
    NULL,
    NULL, true, true
  ),
  (
    'DN', 'Ngon Thị Hoa Restaurant', 'Ngũ Hành Sơn',
    '100 Lê Quang Đạo, Ngũ Hành Sơn, Đà Nẵng',
    'https://maps.app.goo.gl/NYCDTDvweyRQqyJw9',
    'Ẩm thực',
    'Ẩm thực Việt ba miền, Hoài cổ, Sân vườn, Ấm cúng',
    2, '06:00', '22:00', 'Không nghỉ', '+84 96 722 0100',
    'Nhà hàng ẩm thực Việt cảm hứng ba miền — không gian sân vườn mang nét Hội An với trải nghiệm thưởng thức món Việt truyền thống.',
    NULL,
    NULL, true, true
  ),
  (
    'DN', 'Bếp Cuốn', 'An Hải',
    '31-33 Trần Bạch Đằng, An Hải, Đà Nẵng',
    'https://maps.app.goo.gl/khbPUCQ69vH5fb269',
    'Ẩm thực',
    'Ẩm thực Việt truyền thống, Bánh cuốn, Đặc sản địa phương, Mộc mạc',
    2, '10:30', '21:00', 'Không nghỉ', '+84 70 268 9989',
    'Nhà hàng ẩm thực Việt nổi bật với các món cuốn và đặc sản địa phương trong không gian mộc mạc gần gũi.',
    NULL,
    NULL, true, true
  ),
  (
    'DN', 'Bảo Tàng Văn Hóa Sa Huỳnh', 'Hội An',
    '149 Trần Phú, Phố cổ, Hội An, Quảng Nam',
    'https://maps.app.goo.gl/G5bmDaZQpSve5yWL8',
    'Tham quan, Lịch sử',
    'Văn hóa Sa Huỳnh, Lịch sử cổ đại, Di sản Hội An, Khảo cổ',
    1, '08:00', '17:00', 'Ngày 10 hàng tháng', NULL,
    'Bảo tàng lưu giữ hiện vật nền văn hoá Sa Huỳnh hơn 2.000 năm trước — trải nghiệm khám phá lịch sử và sự hình thành của vùng đất Hội An. Vé thường nằm trong vé phố cổ Hội An.',
    NULL,
    NULL, true, true
  ),
  (
    'DN', 'Làng Rau Trà Quế', 'Hội An',
    'Xã Cẩm Hà, Hội An, Quảng Nam',
    'https://maps.app.goo.gl/FmbXvzio6FbnxBQQ9',
    'Trải nghiệm, Làng nghề',
    'Làng nghề, Nông nghiệp hữu cơ, Yên tĩnh, Xanh mát',
    1, '09:00', '18:00', 'Không nghỉ', NULL,
    'Làng rau truyền thống được vinh danh làng du lịch tốt nhất thế giới năm 2024 — trải nghiệm làm nông hữu cơ và khám phá văn hoá nông nghiệp địa phương.',
    'Ngôi làng xanh mát gần Hội An giữ nét trồng rau hữu cơ truyền thống lâu đời. Mỗi mùa mang vẻ đẹp riêng — mỗi hộ dân đều gắn với nghề trồng rau từ cha ông truyền lại. Cách phố cổ khoảng 3km.',
    NULL, true, true
  ),
  (
    'DN', 'Nhà Cổ Tân Kỳ', 'Hội An',
    '101 Nguyễn Thái Học, Phố cổ, Hội An, Quảng Nam',
    NULL,
    'Trải nghiệm',
    'Di sản văn hóa, Kiến trúc giao thoa, Hội An cổ',
    1, '08:30', '17:45', 'Không nghỉ', '+84 235 386 1474',
    'Nhà cổ hơn 200 năm tuổi tại Hội An — kiến trúc giao thoa Việt Nam - Nhật Bản - Trung Hoa lưu giữ giá trị văn hoá thương cảng xưa. Vé 35.000đ/người.',
    NULL,
    NULL, true, true
  ),
  (
    'DN', 'Leaf Village & Farm', 'Hải Vân',
    'Suối Khe Đào, ĐT601, Thôn Nam Mỹ, Hải Vân, Đà Nẵng',
    NULL,
    'Trải nghiệm, Nghỉ dưỡng',
    'Sinh thái chữa lành, Nông trại, Thiên nhiên, Suối rừng',
    2, '05:00', '22:00', 'Không nghỉ', '+84 77 756 8586',
    'Khu nghỉ dưỡng nông trại giữa thiên nhiên Đà Nẵng — trải nghiệm sinh thái và lưu trú gần gũi núi rừng. Vào cổng từ 150.000đ/người. Lưu trú từ 350.000đ/đêm.',
    NULL,
    NULL, true, true
  ),
  (
    'DN', 'The Farmers', 'Bà Nà',
    'Đường Vạn Thành, Thôn Đông Sơn, Bà Nà, Đà Nẵng',
    NULL,
    'Trải nghiệm',
    'Thiên nhiên sinh thái, Nông trại ngoại ô, Thư giãn',
    1, '07:30', '19:00', 'T2, T3, T4, T5 (thường)', '+84 86 712 2256',
    'Không gian nông trại ngoại ô kết hợp trải nghiệm ngoài trời — tham gia các hoạt động thư giãn và khám phá đời sống nông nghiệp gần Bà Nà. Giá ~95.000đ/người gồm 1 đồ uống.',
    NULL,
    NULL, true, true
  ),
  (
    'DN', 'Hội Quán Phước Kiến', 'Hội An',
    '46 Trần Phú, Phố cổ, Hội An, Quảng Nam',
    NULL,
    'Trải nghiệm',
    'Di sản văn hóa, Kiến trúc Trung Hoa, Cổ kính, Tâm linh',
    1, '07:00', '17:00', 'Không nghỉ', '+84 84 342 8888',
    'Hội quán Trung Hoa cổ hơn 300 năm tại Hội An — kiến trúc tinh xảo và không gian thờ tự trang nghiêm gắn với cộng đồng người Hoa. Vé trong vé phố cổ Hội An.',
    'Hội quán Phước Kiến mang đậm dấu ấn kiến trúc và đời sống tinh thần của cộng đồng người Hoa tại Hội An. Nổi bật với cổng tam quan, sân trong rộng và các chi tiết chạm khắc tinh xảo. Phản ánh rõ nét lịch sử giao thương và sự giao thoa văn hoá của thương cảng Hội An qua nhiều thế kỷ.',
    NULL, true, true
  ),
  (
    'DN', 'Bảo Tàng Đồng Đình', 'Sơn Trà',
    'Đường Hoàng Sa, Sơn Trà, Đà Nẵng',
    NULL,
    'Trải nghiệm',
    'Văn hóa hoài niệm, Nghệ thuật, Thiên nhiên, Đồ cổ',
    1, '07:30', '18:00', 'Không nghỉ', '+84 90 113 7111',
    'Bảo tàng kết hợp thiên nhiên - nghệ thuật - văn hóa truyền thống trong không gian rừng xanh mát trên Bán đảo Sơn Trà. Vé 35.000đ/người.',
    NULL,
    NULL, true, true
  ),
  (
    'DN', 'Nhà Gỗ Villa', 'Ngũ Hành Sơn',
    'Lô 06 Khu B3-78, Khu đô thị FPT City, Ngũ Hành Sơn, Đà Nẵng',
    NULL,
    'Lưu trú, Nghỉ dưỡng',
    'Kiến trúc gỗ, Chữa lành, Yên tĩnh, Hồ bơi riêng',
    4, '14:00', '12:00', 'Không nghỉ', '+84 85 672 7631',
    'Villa glamping kiến trúc gỗ mộc giữa không gian xanh — hồ bơi riêng và trải nghiệm lưu trú gần gũi thiên nhiên dành cho nhóm bạn và gia đình. Từ 3.900.000đ/đêm.',
    NULL,
    NULL, true, true
  );
